#ifndef CEPHES_NAMES_H
#define CEPHES_NAMES_H

/* cephes/acosh.c */
#define acosh cephes_acosh
/* cephes/airy.c */
#define airy cephes_airy
/* cephes/asin.c */
#define asin cephes_asin
#define acos cephes_acos
/* cephes/asinh.c */
#define asinh cephes_asinh
/* cephes/atan.c */
#define atan cephes_atan
#define atan2 cephes_atan2
/* cephes/atanh.c */
#define atanh cephes_atanh
/* cephes/bdtr.c */
#define bdtrc cephes_bdtrc
#define bdtr cephes_bdtr
#define bdtri cephes_bdtri
/* cephes/beta.c */
#define beta cephes_beta
#define lbeta cephes_lbeta
/* cephes/btdtr.c */
#define btdtr cephes_btdtr
/* cephes/cbrt.c */
#define cbrt cephes_cbrt
/* cephes/chbevl.c */
#define chbevl cephes_chbevl
/* cephes/chdtr.c */
#define chdtrc cephes_chdtrc
#define chdtr cephes_chdtr
#define chdtri cephes_chdtri
/* cephes/const.c */
/* cephes/cosh.c */
#define cosh cephes_cosh
/* cephes/dawsn.c */
#define dawsn cephes_dawsn
/* cephes/ei.c */
#define ei cephes_ei
/* cephes/ellie.c */
#define ellie cephes_ellie
/* cephes/ellik.c */
#define ellik cephes_ellik
/* cephes/ellpe.c */
#define ellpe cephes_ellpe
/* cephes/ellpj.c */
#define ellpj cephes_ellpj
/* cephes/ellpk.c */
#define ellpk cephes_ellpk
/* cephes/exp.c */
#define exp cephes_exp
/* cephes/exp10.c */
#define exp10 cephes_exp10
/* cephes/exp2.c */
#define exp2 cephes_exp2
/* cephes/expn.c */
#define expn cephes_expn
/* cephes/expx2.c */
#define expx2 cephes_expx2
/* cephes/fac.c */
#define fac cephes_fac
/* cephes/fdtr.c */
#define fdtrc cephes_fdtrc
#define fdtr cephes_fdtr
#define fdtri cephes_fdtri
/* cephes/floor.c */
#define frexp cephes_frexp
#define ldexp cephes_ldexp
/* cephes/fresnl.c */
#define fresnl cephes_fresnl
/* cephes/gamma.c */
#define gamma cephes_gamma
#define lgam cephes_lgam
/* cephes/gdtr.c */
#define gdtr cephes_gdtr
#define gdtrc cephes_gdtrc
/* cephes/hyp2f1.c */
#define hyp2f1 cephes_hyp2f1
/* cephes/hyperg.c */
#define hyperg cephes_hyperg
#define hyp2f0 cephes_hyp2f0
/* cephes/i0.c */
#define i0 cephes_i0
#define i0e cephes_i0e
/* cephes/i1.c */
#define i1 cephes_i1
#define i1e cephes_i1e
/* cephes/igam.c */
#define igamc cephes_igamc
#define igam cephes_igam
/* cephes/igami.c */
#define igami cephes_igami
/* cephes/incbet.c */
#define incbet cephes_incbet
/* cephes/incbi.c */
#define incbi cephes_incbi
/* cephes/isnan.c */
#define signbit cephes_signbit
#define isnan cephes_isnan
#define isfinite cephes_isfinite
/* cephes/iv.c */
#define iv cephes_iv
/* cephes/j0.c */
#define j0 cephes_j0
#define y0 cephes_y0
/* cephes/j1.c */
#define j1 cephes_j1
#define y1 cephes_y1
/* cephes/jn.c */
#define jn cephes_jn
/* cephes/jv.c */
#define jv cephes_jv
/* cephes/k0.c */
#define k0 cephes_k0
#define k0e cephes_k0e
/* cephes/k1.c */
#define k1 cephes_k1
#define k1e cephes_k1e
/* cephes/kn.c */
#define kn cephes_kn
/* cephes/kolmogorov.c */
#define smirnov cephes_smirnov
#define kolmogorov cephes_kolmogorov
#define smirnovi cephes_smirnovi
#define kolmogi cephes_kolmogi
/* cephes/log.c */
#define log cephes_log
/* cephes/log10.c */
#define log10 cephes_log10
/* cephes/log2.c */
#define log2 cephes_log2
/* cephes/nbdtr.c */
#define nbdtrc cephes_nbdtrc
#define nbdtr cephes_nbdtr
#define nbdtri cephes_nbdtri
/* cephes/ndtr.c */
#define ndtr cephes_ndtr
#define erfc cephes_erfc
#define erf cephes_erf
/* cephes/ndtri.c */
#define ndtri cephes_ndtri
/* cephes/pdtr.c */
#define pdtrc cephes_pdtrc
#define pdtr cephes_pdtr
#define pdtri cephes_pdtri
/* cephes/planck.c */
#define plancki cephes_plancki
#define planckc cephes_planckc
#define planckd cephes_planckd
#define planckw cephes_planckw
/* cephes/polevl.c */
#define polevl cephes_polevl
#define p1evl cephes_p1evl
/* cephes/polylog.c */
#define polylog cephes_polylog
/* cephes/pow.c */
#define pow cephes_pow
/* cephes/powi.c */
#define powi cephes_powi
/* cephes/psi.c */
#define psi cephes_psi
/* cephes/rgamma.c */
#define rgamma cephes_rgamma
/* cephes/round.c */
#define round cephes_round
/* cephes/shichi.c */
#define shichi cephes_shichi
/* cephes/sici.c */
#define sici cephes_sici
/* cephes/sin.c */
#define sin cephes_sin
#define cos cephes_cos
#define radian cephes_radian
/* cephes/sincos.c */
#define sincos cephes_sincos
/* cephes/sindg.c */
#define sindg cephes_sindg
#define cosdg cephes_cosdg
/* cephes/sinh.c */
#define sinh cephes_sinh
/* cephes/spence.c */
#define spence cephes_spence
/* cephes/stdtr.c */
#define stdtr cephes_stdtr
#define stdtri cephes_stdtri
/* cephes/struve.c */
#define onef2 cephes_onef2
#define threef0 cephes_threef0
#define struve cephes_struve
#define yv cephes_yv
/* cephes/tan.c */
#define tan cephes_tan
#define cot cephes_cot
/* cephes/tandg.c */
#define tandg cephes_tandg
#define cotdg cephes_cotdg
/* cephes/tanh.c */
#define tanh cephes_tanh
/* cephes/unity.c */
#define log1p cephes_log1p
#define expm1 cephes_expm1
#define cosm1 cephes_cosm1
/* cephes/yn.c */
#define yn cephes_yn
/* cephes/zeta.c */
#define zeta cephes_zeta
/* cephes/zetac.c */
#define zetac cephes_zetac

#endif


