name: Continuous Integration

on: 
  push:
   branches:
    - master
  pull_request:

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install clang
        run: | 
          npm install -g clang-format
          npm install --save-dev husky
      - name: install cproto
        run: |
          wget -c https://sourceforge.net/projects/cproto/files/cproto/4.6/cproto-4.6.tar.gz -O - | tar -xz
          sudo apt-get install cproto
          echo "downloaded and installed cproto" 
      - name: install emscripten
        run: |

          # Install Python
          sudo apt-get update -y
          sudo apt-get install python3  
          sudo apt-get install cmake        
          #sudo apt-get install clangd-12
          #sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-12 100

          #sudo apt update 
          #sudo apt install clang
          #sudo apt install llvm
          #export CC=clang
          

          # sudo apt-get install libllvm-17-ocaml-dev libllvm17 llvm-17 llvm-17-dev llvm-17-doc llvm-17-examples llvm-17-runtime
          # sudo apt-get install clang-17 clang-tools-17 clang-17-doc libclang-common-17-dev libclang-17-dev libclang1-17 clang-format-17 python3-clang-17 clangd-17 clang-tidy-17
          # sudo apt-get install lldb-17
          # sudo apt-get install libc++-17-dev libc++abi-17-dev
          # sudo apt-get install libclang-rt-17-dev-wasm32 libclang-rt-17-dev-wasm64 libc++-17-dev-wasm32 libc++abi-17-dev-wasm32 libclang-rt-17-dev-wasm32 libclang-rt-17-dev-wasm64


          # wget https://apt.llvm.org/llvm.sh
          # chmod +x llvm.sh

          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull
          
          # Install & activate latest SDK
          # See https://emscripten.org/docs/getting_started/downloads.html for more details
          
          ./emsdk install latest 
          ./emsdk activate latest    
          # Add to .bashrc and .zshrc
          if [[ -f "~/.bashrc" ]]; then echo -e "\n source ~/.emsdk/emsdk_env.sh" >> ~/.bashrc; fi
          if [[ -f "~/.zshrc" ]]; then echo -e "\n source ~/.emsdk/emsdk_env.sh" >> ~/.zshrc; fi
          cd ..
          #To install all apt.llvm.org packages at once:
          sudo apt-get update

          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh all
            
          echo "downloaded and installed emscripten"
      - name: install dependencies and build
        run: |
          npm install
          make download
          make build
      - name: test
        run: | 
          npm test
