name: Continuous Integration

on:
  push:
   branches:
    - master
  pull_request:

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install build tools
        run: |
          sudo apt-get update && sudo apt-get install -y clang-format cproto git cmake python3 curl libtinfo5
          npm install -g clang-tools-prebuilt

          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk && ./emsdk install 3.1.57 && ./emsdk activate 3.1.57 && source ./emsdk_env.sh && cd ..
          
          yarn
          make build
      - name: test
        run: | 
          yarn test
